# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    outputs:
      result: ${{ steps.fastr.outputs.result }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: FAST-R Test Reduction for PyTest
        id: fastr
        # You may pin to the exact commit or the version.
        # uses: jrcamelo/fast-r-action@db5d22a65b248b7cf5b8b59c6cf22c179d9fcb0b
        uses: jrcamelo/fast-r-action@test69
        
  comment:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Sticky Pull Request Comment
          # You may pin to the exact commit or the version.
          # uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443
          uses: marocchino/sticky-pull-request-comment@v2.2.0
          with:
            message: ${{ needs.build.outputs.result }}
      
